# Generated by Django 5.2 on 2025-04-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_page', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=50)),
                ('book', models.FileField(upload_to='')),
            ],
        ),
    ]
